# RUTAS FIJAS

server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: auditorias
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/auditoria/**

          - id: beneficiarios
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/beneficiarios/**
          - id: comunas
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/comunas/**
          - id: regiones
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/regiones/**

          - id: centros
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/centros/**

          - id: distribucion
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/distribuciones/**

          - id: donacion
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/donaciones/**
          - id: tipodonacion
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/tipodonacion/**

          - id: emergencias
            uri: http://localhost:8086
            predicates:
              - Path=/api/v1/emergencias/**

          - id: inventario
            uri: http://localhost:8087
            predicates:
              - Path=/api/v1/inventarios/**

          - id: transporte
            uri: http://localhost:8088
            predicates:
              - Path=/api/v1/vehiculos/**

          - id: usuarios
            uri: http://localhost:8089
            predicates:
              - Path=/api/v1/usuarios/**
          - id: roles
            uri: http://localhost:8089
            predicates:
              - Path=/api/v1/roles/**

          - id: voluntarios
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/voluntarios/**
          - id: asignaciones
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/asignaciones/**
